services:
  postgres:
    build: .
    environment:
      POSTGRES_USER: myuser          # <- Required to create role
      POSTGRES_PASSWORD: mypassword  # <- Required to set password
      POSTGRES_DB: baseball
      PGHOST: localhost
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/app/data
      - ../data:/app/all_data
      - ./scripts:/app/scripts
    command: [
      "postgres",
      "-c", "shared_preload_libraries=auto_explain",
      "-c", "auto_explain.log_min_duration=0",
      "-c", "auto_explain.log_analyze=on",
      "-c", "auto_explain.log_verbose=on",
      "-c", "auto_explain.log_nested_statements=on",
      "-c", "auto_explain.log_triggers=on",
      "-c", "auto_explain.log_buffers=on",
      "-c", "client_min_messages=log"
    ]

volumes:
  pgdata:
