services:
  postgres:
    build: .
    environment:
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: baseball
      PGHOST: localhost
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./data:/app/data
      - ./scripts:/app/scripts
