# Dockerfile.bench
FROM python:3.10-slim

# Install psycopg2 (and any other deps)
RUN apt-get update && apt-get install -y --no-install-recommends \
      gcc libpq-dev \
    && pip install --no-cache-dir psycopg2-binary \
    && apt-get purge -y --auto-remove gcc

# Create a directory inside the container
WORKDIR /app/scripts

# Default command: run the benchmark script
ENTRYPOINT ["sh", "-c", "python collect-metrics.py || tail -f /dev/null"]